PACKAGE_NAME="insyde-efivarfs"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="insyde_efivarfs"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
MAKE[0]="make KERNEL_RELEASE=${kernelver} KERNEL_BUILD=${kernel_source_dir}"
